#!/bin/bash
# /home/oracle/backupBDs-VM
BKORIGEM="/home/oracle/backup"
BKDESTINO="/mnt/backups/backup"
LOG="/mnt/backups/logs/`date +%Y-%m-%d`_backup.txt"
INICIO=`date +%d/%m/%Y-%H:%M:%S`

echo "Sincronização iniciada em $INICIO " >> $LOG

# Efetua a cópia dos arquivos de backup 
rsync -uahv ${BKORIGEM}/*zip ${BKDESTINO} >> $LOG

# Apaga arquivos antigos (mais que 1 dia)
find ${BKORIGEM} -mtime +0 -exec rm -rf {} +; >> $LOG

# Apaga arquivos antigos (mais que 10 dias)
find ${BKDESTINO} -mtime +10 -exec rm -rf {} +; >> $LOG

FIM=`date +%d/%m/%Y-%H:%M:%S`
echo "Sincronização finalizada em $FIM " >> $LOG

exit 0
